### ISSUE TITLE
License

### ISSUE THREAD

**Issue by starseeker** [AnkaChan/Shortest-Path-to-Boundary-for-Self-Intersecting-Meshes#1]
Hi!  Could you tell us what license is being used for this code?

**Comment by AnkaChan** [comment]
Hello, I just updated the license. It's Apache 2.0.

**Comment by starseeker** [comment]
A related question - since MeshFrame2 is GPL, the overall code stack is only usable in GPL compatible situations currently... is there a potential alternative to MeshFrame2 that the code could be ported to?

Also, is CuMatrix also Apache 2.0?

**Comment by AnkaChan** [comment]
Hi, thank you for pointing this out; I will switch the License of those libraries to Apache 2.0 as well.
By the way, the code in this library is not maintained. If you want the newest version of the discrete collision detector, please go to Gaia Engine: https://github.com/AnkaChan/Gaia. Where this part of the code is incorporated as the discrete collision detector.
